sudo: false

language: c

compiler:
  - gcc-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-4.8
      - gcc-4.8
      - libopenblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - openmpi-bin

script:
  - ./bootstrap
  - F77="gfortran-4.8" CFLAGS="-fno-omit-frame-pointer -fsanitize=address" ./configure --enable-mpi
  - make all
  - make check
  - make distcheck
