sudo: false

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
      - gfortran
      - libopenblas-dev
      - liblapack-dev
      - libopenmpi-dev
      - openmpi-bin

script:
  - ./bootstrap
  - CFLAGS="-fno-omit-frame-pointer -fsanitize=address" ./configure --enable-mpi
  - make all
  - make check
  - make distcheck
